### ISSUE TITLE
Automatically and selectively use HTTP(S) proxy

### ISSUE THREAD

**Issue by abyrne55** [mjlshen/mirrosa#346]
Tried to use mirrosa (nightly) with an HTTP(S) proxy configuration, like so:
```bash
export HTTPS_PROXY=squid.company.com:3128
export HTTP_PROXY=squid.company.com:3128
./mirrosa -v -cluster-id $CID
```
But I received an error that seems to indicate there are some URLs that should not be accessed via proxy
```
time=2024-01-30T13:59:32.566-05:00 level=DEBUG source=github.com/mjlshen/mirrosa/main.go:31 msg="Go Version: go1.21.6"
time=2024-01-30T13:59:32.566-05:00 level=DEBUG source=github.com/mjlshen/mirrosa/main.go:34 msg="Git SHA: 4fc53f89eb512fe498378ccbd2e8c0ac2493ac5b"
time=2024-01-30T13:59:32.566-05:00 level=DEBUG source=github.com/mjlshen/mirrosa/main.go:37 msg="From: 2024-01-29T05:51:23Z"
WARN[0001] Manual URL configuration is deprecated, please remove URL key from Backplane configuration 
INFO[0002] Backplane URL retrieved via OCM environment: https://api.backplane.openshift.com 
time=2024-01-30T13:59:35.439-05:00 level=ERROR source=github.com/mjlshen/mirrosa/main.go:57 msg="failed to generate cloud credentials: Get \"https://api.backplane.openshift.com/backplane/cloud/credentials/<CLUSTER_ID_REDACTED>\": proxyconnect tcp: dial tcp :0: connect: connection refused"
```
Could we implement selective proxy usage similar to osdctl?

**Comment by mjlshen** [comment]
I'm not actually familiar with the selective proxy in osdctl - what are you trying to selectively proxy (or what are you trying to selectively not proxy)?

**Comment by abyrne55** [comment]
osdctl has an `aws_proxy` directive in its config file where users can specify the HTTP proxy that all AWS API calls should be routed through. It also [warns](https://github.com/openshift/osdctl/blob/4615855a37652c34cf5feaf347334fa0fceba626/pkg/provider/aws/client.go#L152-L177) the user when this isn't configured. I think it'd be great for mirrosa to have similar functionality to prevent accidental out-of-proxy access.
(I admit I could have worded this better, as "selective proxy" makes the feature sound fancier than it is 😅)

I should also clarify that I'm happy to cook up a PR for this myself. I just wanted to run the idea by you first and get your input on how I should implement it.

**Comment by typeid** [comment]
I also needed this during my shift, so I quickly drafted a PR. It doesn't incorporate the warning @abyrne55 suggested when not using the proxy, but I think it's fair to not have it considering that this tool is not meant specifically for Red Hat internal usage.

**Comment by mjlshen** [comment]
Ah, if the concern is around whether mirrosa proxies AWS calls at all, currently mirrosa mostly inherits proxying AWS calls via backplane-cli:

https://github.com/mjlshen/mirrosa/blob/49602aa608eb70aa9b49b8414df7b3659291448c/pkg/ocm/ocm.go#L54-L68
-->
https://github.com/openshift/backplane-cli/blob/28ed0cd5bd0bfc6e905922c79493164db56eddc5/pkg/credentials/aws.go#L47-L74

Do we have a use-case for overriding the proxy specified for backplane? Not opposed to adding it if it there's a use-case there.

**Comment by typeid** [comment]
I was not aware of that. That makes sense and satisfies my need. :)
